FROM node:13.7 as builder

WORKDIR /app
EXPOSE 80

COPY package*.json /app/
RUN npm install
COPY ./ /app/

RUN npm run build

FROM nginx:1.16-alpine

COPY --from=builder /app/build/ /usr/share/nginx/html/
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d

CMD ["nginx", "-g", "daemon off;"]
