version: "3.7"

services:
  api:
    image: ghcr.io/happy-appy/happy-appy-api
    env_file:
      - ./.env.prod

  frontend:
    image: ghcr.io/happy-appy/happy-appy-frontend

  nginx:
    image: ghcr.io/happy-appy/happy-appy-nginx
    networks:
      - default
      - nginx-network
    depends_on:
      - api
      - frontend

networks:
  nginx-network:
    external:
      name: nginx-network
