version: "3.7"

services:
  api:
    build: ./api
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:11.6
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/static:/static
    ports:
      - 80:80
    depends_on:
      - api

volumes:
  postgres_data:
