version: '3.7'

services:

  api:
    build: ./api
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    expose:
      - 80

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    volumes:
      - ./api/static:/static
    ports:
      - 80:80
    depends_on:
      - api
      - frontend
