version: '3.7'

services:

  api:
    build: ./api
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    volumes:
      - ./api/static:/static
      - frontend_data:/frontend
    ports:
      - 80:80
    depends_on:
      - api
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - frontend_data:/app/build

volumes:
  frontend_data:
