version: '3.7'

services:

  api:
    build: ./api
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./api:/usr/src/app
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:11.6
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    volumes:
      - ./api/static:/static
    ports:
      - 80:80
    depends_on:
      - api

volumes:
  postgres_data:

