name: CI/CD

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    env:
      REGISTRY_PATH: docker.pkg.github.com/${{ github.repository }}

    steps:
      - uses: actions/checkout@v2

      - name: Get SHA7
        id: vars
        run: echo "::set-output name=SHA7::$(git rev-parse --short HEAD)"

      - name: Build docker images
        run: |
          docker network create nginx-network
          docker build --file api/Dockerfile \
          --tag $REGISTRY_PATH/api:${{ steps.vars.outputs.SHA7 }} api
          docker build --file frontend/Dockerfile.prod \
          --tag $REGISTRY_PATH/frontend:${{ steps.vars.outputs.SHA7 }} frontend
          docker build --file nginx/Dockerfile.prod \
          --tag $REGISTRY_PATH/nginx:${{ steps.vars.outputs.SHA7 }} \
          --network nginx-network --network default nginx

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push images
        run: |
          docker push $REGISTRY_PATH/api:${{ steps.vars.outputs.SHA7 }}
          docker push $REGISTRY_PATH/frontend:${{ steps.vars.outputs.SHA7 }}
          docker push $REGISTRY_PATH/nginx:${{ steps.vars.outputs.SHA7 }}

  test:
    needs: build

    runs-on: ubuntu-18.04

    env:
      REGISTRY_PATH: docker.pkg.github.com/${{ github.repository }}

    steps:
      - uses: actions/checkout@v2

      - name: Get SHA7
        id: vars
        run: echo "::set-output name=SHA7::$(git rev-parse --short HEAD)"

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Pull docker image
        run: docker pull $REGISTRY_PATH/api:${{ steps.vars.outputs.SHA7 }}

      - name: Run tests
        run: |
          docker run --env SECRET_KEY=${{ secrets.SECRET_KEY }} --env DEBUG=0 \
          --env DJANGO_ALLOWED_HOSTS=happyappy.darylforbes.me \
          --env POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          --env POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
          --env POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          --env POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
          $REGISTRY_PATH/api:${{ steps.vars.outputs.SHA7 }} pytest
  push:
    needs: test

    runs-on: ubuntu-18.04

    env:
      REGISTRY_PATH: docker.pkg.github.com/${{ github.repository }}

    steps:
      - uses: actions/checkout@v2

      - name: Get SHA7
        id: vars
        run: echo "::set-output name=SHA7::$(git rev-parse --short HEAD)"

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Pull docker images
        run: |
          docker pull $REGISTRY_PATH/api:${{ steps.vars.outputs.SHA7 }}
          docker pull $REGISTRY_PATH/frontend:${{ steps.vars.outputs.SHA7 }}
          docker pull $REGISTRY_PATH/nginx:${{ steps.vars.outputs.SHA7 }}

      - name: Tag images
        run: |
          docker tag $REGISTRY_PATH/api:${{ steps.vars.outputs.SHA7 }} \
          $REGISTRY_PATH/api:latest
          docker tag $REGISTRY_PATH/frontend:${{ steps.vars.outputs.SHA7 }} \
          $REGISTRY_PATH/frontend:latest
          docker tag $REGISTRY_PATH/nginx:${{ steps.vars.outputs.SHA7 }} \
          $REGISTRY_PATH/nginx:latest

      - name: Push images
        run: |
          docker push $REGISTRY_PATH/api:latest
          docker push $REGISTRY_PATH/frontend:latest
          docker push $REGISTRY_PATH/nginx:latest
